name: Python Test and Package

on:
  pull_request:
    branches:
      - main

jobs:
  lint_test:
    strategy:
      matrix:
        os:
          [
            "ubuntu-latest",
            "ubuntu-16.04",
            "ubuntu-18.04",
            "windows-latest",
            "windows-2016",
            "macos-latest",
          ]
        python-version: [3.6, 3.7]
        kedro-versions: ["kedro"] # only compatable with the 0.16.x since hooks were introduced
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install requirements
          pip install -r requirements.txt
          # pip install ${{ matrix.kedro-versions }}
          pip install -r requirements_dev.txt
          python setup.py install
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: type checking with mypy
        run: mypy steel_toes
      - name: check fully documented
        run: interrogate -f 100 -vv --exclude punch_version.py
      - name: Test with pytest
        run: pytest
  build:
    runs-on: ubuntu-latest
    needs: lint_test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: build
        run: pip install wheel && python setup.py sdist bdist_wheel
      - name: pypi-publish
        # if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          # PyPI user
          # Password for your PyPI user or an access token
          password: ${{ secrets.pypi_password }}
          # The repository URL to use
          # repository_url: # optional
          # The target directory for distribution
          # packages_dir: # optional, default is dist
